spring:
  jpa:
    hibernate:
      format_sql: true
      use_sql_comments: true
      ddl-auto: create
    show-sql: true
    database: postgresql
  datasource:
    #    url: jdbc:h2:mem:testdb
    url: jdbc:postgresql://localhost:5432/sideproject_db
    username: sideproject
    password: 20251220!
    driver-class-name: org.postgresql.Driver
  #  h2:
  #    console:
  #      enabled: true
  defer-datasource-initialization: true
